name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose
      - name: Build docs
        run: cargo doc --no-deps --target-dir="/tmp/cargo-doc"
      - name: Publish docs
        run: |
          set -ex
          git fetch origin gh-pages
          git checkout gh-pages
          git clean -f -X
          mv /tmp/cargo-doc/doc/* .
          git add .
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git commit -m "Docs build $GITHUB_SHA"
          git push origin gh-pages
